id: 1c769646543648029844eedee5912df2
initial_creation_type: ocr
source_metadata:
  volumes:
    38fca9fa5c59463a93722df8527267ca:
      base_file: v011.txt
      image_group_id: I1PD95856
      title: ''
      total_pages: 2107
      volume_number: 11
